/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bulls;

import org.junit.Ignore;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {

    }
}
